import styles from './formulario.module.css'
import Head from 'next/head'

export default function Formulario() {
    return (
      <div className ={styles.form}>
        <Head>
          <title>Formulario</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <h1>
         <a href="formulario.js"></a>
        </h1>
        <form>
         <ul> <label for="nome">Nome:</label>
          <input id="nome"/>
        </ul>

        <ul>
          <label for="parte1">Email:</label>
          <input id="parte1"/>

          </ul>

          <ul> <label for="parte2">Telefone:</label>
          <input id="parte2"/>
        </ul>

        <ul>
          <label for="parte3">Mensagem:</label>
          <input id="parte3"/>

          </ul>
        </form>
      </div>
    )
}