import styles from './inicio.module.css'
import Head from 'next/head'
export default function Inicio() {
  return (
    <div>


      

      <div className={styles.image}>
        <Head>
          <title>Portifolio</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <h1 className={styles.pname}>Bruno Rocha Ferreira
         <p></p>
        </h1>

      </div>

     
    </div>

    
  )
}